# Generated by Django 4.1.7 on 2023-03-23 03:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2023, 3, 22, 22, 35, 35, 908225))),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.6', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2023, 3, 22, 22, 35, 35, 909226))),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.6', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Maestrias',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2023, 3, 22, 22, 35, 35, 909226))),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.6', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sede',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2023, 3, 22, 22, 35, 35, 909226))),
                ('fechaModificado', models.DateField(auto_now=True, null=True)),
                ('fechaElimnado', models.DateField(blank=True, null=True)),
                ('ipUsuario', models.CharField(blank=True, default='192.168.1.6', max_length=100, null=True)),
                ('usuarioPosgradoFIM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Documentos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('numeroDocumento', models.CharField(max_length=100)),
                ('numeroUbigeoNacimiento', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('codigoEgresadoUNI', models.CharField(max_length=20)),
                ('primerNombre', models.CharField(max_length=100)),
                ('segundoNombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('correoUNI', models.CharField(blank=True, max_length=100, null=True)),
                ('gradoEstudio', models.CharField(max_length=200)),
                ('universidadProcedencia', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('estadoCivil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.estadocivil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('maestria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.maestria')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.sede')),
                ('tipoDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.tipodocumento')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
