# Generated by Django 4.1.7 on 2023-03-23 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfimapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 22, 46, 49, 834176)),
        ),
        migrations.AlterField(
            model_name='maestria',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 22, 46, 49, 835177)),
        ),
        migrations.AlterField(
            model_name='sede',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 22, 46, 49, 835177)),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 22, 46, 49, 835177)),
        ),
    ]
